package coding

import (
	"fmt"
	"os"
	"path/filepath"
)

// OpenCode is the coding agent implementation for opencode.
type OpenCode struct{}

func init() {
	Register(&OpenCode{})
}

func (o *OpenCode) Name() string {
	return "opencode"
}

func (o *OpenCode) Command() string {
	return "opencode"
}

func (o *OpenCode) HookPath() string {
	configDir, err := os.UserConfigDir()
	if err != nil {
		return ""
	}
	return filepath.Join(configDir, "opencode", "plugins", "agents-hook.js")
}

func (o *OpenCode) Hook(agentsBinary string) string {
	return fmt.Sprintf(`// Auto-generated by agents — do not edit manually.
// Version: %s
//
// This plugin reports coding agent status back to the agents watcher.

export const AgentsPlugin = async ({ worktree, $ }) => {
  const agents = %q;
  const wt = worktree;

  const update = async (status) => {
    try {
      await $`+"`"+`${agents} update-status --worktree ${wt} --status ${status}`+"`"+`;
    } catch (e) {
      // Silently ignore — agents might not be running.
    }
  };

  // Report idle on startup.
  await update("idle");

  return {
    event: async ({ event }) => {
      switch (event.type) {
        case "session.status":
          // session.status fires when the agent starts/stops working.
          await update("working");
          break;
        case "session.idle":
          await update("idle");
          break;
        case "session.error":
          await update("waiting");
          break;
        case "permission.asked":
          await update("waiting");
          break;
        case "permission.replied":
          await update("working");
          break;
      }
    },
  };
};
`, HookVersion, agentsBinary)
}
