package coding

import (
	"fmt"
	"os"
	"path/filepath"
)

// OpenCode is the coding agent implementation for opencode.
type OpenCode struct{}

func init() {
	Register(&OpenCode{})
}

func (o *OpenCode) Name() string {
	return "opencode"
}

func (o *OpenCode) Command() string {
	return "opencode"
}

func (o *OpenCode) HookPath() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	return filepath.Join(home, ".config", "opencode", "plugins", "agents-hook.js")
}

func (o *OpenCode) Hook(agentsBinary string) string {
	return fmt.Sprintf(`// Auto-generated by agents — do not edit manually.
// Version: %s
//
// This plugin reports coding agent status back to the agents watcher.

export const AgentsPlugin = async ({ worktree, $ }) => {
  const agents = %q;
  const panePid = String(process.ppid);
  const paneId = process.env.TMUX_PANE ?? "";
  const workdir = process.cwd();

  let lastStatus = "";
  const update = async (status) => {
    if (status === lastStatus) return;
    lastStatus = status;
    try {
      await $`+"`"+`${agents} update-status --pane-pid ${panePid} --status ${status}`+"`"+`;
    } catch (e) {
      // Silently ignore — agents might not be running.
    }
  };

  // Register with the watcher and report idle on startup.
  try {
    await $`+"`"+`${agents} register --pane-id ${paneId} --workdir ${workdir} --agent-type opencode`+"`"+`;
  } catch (e) {
    // Silently ignore — agents might not be running.
  }
  await update("idle");

  return {
    "message.updated": async () => {
      await update("working");
    },
    "message.part.updated": async () => {
      await update("working");
    },
    "tool.execute.before": async () => {
      await update("working");
    },
    "session.idle": async () => {
      await update("idle");
    },
    "session.error": async () => {
      await update("waiting");
    },
    "permission.asked": async () => {
      await update("waiting");
    },
    "permission.replied": async () => {
      await update("working");
    },
  };
};
`, HookVersion, agentsBinary)
}
