package coding

import (
	"fmt"
	"os"
	"path/filepath"
)

// Pi is the coding agent implementation for pi.
type Pi struct{}

func init() {
	Register(&Pi{})
}

func (p *Pi) Name() string {
	return "pi"
}

func (p *Pi) Command() string {
	return "pi"
}

func (p *Pi) HookPath() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	// pi auto-discovers extensions from ~/.pi/agent/extensions/
	return filepath.Join(home, ".pi", "agent", "extensions", "agents-hook.ts")
}

func (p *Pi) Hook(agentsBinary string) string {
	return fmt.Sprintf(`// Auto-generated by agents — do not edit manually.
// Version: %s
//
// This extension reports coding agent status back to the agents watcher.

import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";

export default function (pi: ExtensionAPI) {
  const agents = %q;
  const panePid = String(process.ppid);
  const paneId = process.env.TMUX_PANE ?? "";
  const workdir = process.cwd();

  let lastStatus = "";
  const update = async (status: string) => {
    if (status === lastStatus) return;
    lastStatus = status;
    try {
      await pi.exec(agents, ["update-status", "--pane-pid", panePid, "--status", status, "--agent-type", "pi"]);
    } catch {
      // Silently ignore — agents might not be running.
    }
  };

  // Register with the watcher and report idle on startup.
  pi.on("session_start", async (_event, _ctx) => {
    try {
      await pi.exec(agents, ["register", "--pane-id", paneId, "--workdir", workdir, "--agent-type", "pi"]);
    } catch {
      // Silently ignore — agents might not be running.
    }
    await update("idle");
  });

  pi.on("agent_start", async (_event, _ctx) => {
    await update("working");
  });

  pi.on("agent_end", async (_event, _ctx) => {
    await update("idle");
  });

  pi.on("session_shutdown", async (_event, _ctx) => {
    await update("exited");
  });
}
`, HookVersion, agentsBinary)
}
