version: 2

project_name: agents

builds:
  - main: .
    binary: agents
    ldflags:
      - -s -w
      - -X notb.re/agents/cmd.Version={{.Version}}
      - -X notb.re/agents/cmd.Commit={{.ShortCommit}}
      - -X notb.re/agents/cmd.Date={{.Date}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: guillaumebreton
    name: agents
